version: "3"
services:
  jaeger:
    image: jaegertracing/all-in-one:1.38
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778/tcp"
      - "5775:5775/udp"
      - "16686:16686"
      - "16685:16685"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      COLLECTOR_ZIPKIN_HOST_PORT: "9411"
  datacollect:
    build:
      context: ./
    image: asinatra/datacollect-inov-jaeger
    depends_on: 
      - jaeger
    ports:
      - 5000:5000
    user: '1000'
    volumes:
      - ./logs/datacollect:/app/logs
  